CREATE TABLE Afiliados (
    idAfiliado NUMBER GENERATED BY DEFAULT AS IDENTITY,
    tipoDocumento VARCHAR(50) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    fechaNacimiento DATE NOT NULL,
    direccion VARCHAR(250) NOT NULL,
    telefono VARCHAR(15) NOT NULL,
    parentesco VARCHAR(50) NOT NULL,
    tipoAfiliado VARCHAR(50) NOT NULL CHECK (tipoAfiliado IN ('CONTRIBUYENTE','BENEFICIARIO')),
    idContribuyente NUMBER NULL,
    CONSTRAINT pk_Afiliado PRIMARY KEY (idAfiliado),
    FOREIGN KEY (idContribuyente) REFERENCES Afiliados(idAfiliado) ON DELETE SET NULL 
);

CREATE TABLE IPSs(
    nit NUMBER PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    direccion VARCHAR(255) NOT NULL,
    telefono VARCHAR(20) NOT NULL,
    horario VARCHAR(50) NOT NULL
);

CREATE TABLE Medicos(
    idMedico NUMBER GENERATED BY DEFAULT AS IDENTITY,
    identificacion VARCHAR(50) NOT NULL UNIQUE,
    nombre VARCHAR(100) NOT NULL,
    numRegistro VARCHAR(50) NOT NULL UNIQUE,
    especialidad VARCHAR(100) NOT NULL,
    CONSTRAINT pk_medico PRIMARY KEY(idMedico)
);

CREATE TABLE OrdenServicios(
    idOrden NUMBER GENERATED BY DEFAULT AS IDENTITY,
    tipoOrden VARCHAR(250) NOT NULL,
    receta CLOB NOT NULL,
    estado VARCHAR(150) NOT NULL CHECK(estado IN ('VIGENTE','CANCELADA','COMPLETADA')),
    fecha DATE NOT NULL,
    idMedico NUMBER NOT NULL,
    idAfiliado NUMBER NOT NULL,
    CONSTRAINT pk_ordenServicio PRIMARY KEY(idOrden),
    FOREIGN KEY (idMedico) REFERENCES Medicos(idMedico),
    FOREIGN KEY (idAfiliado) REFERENCES Afiliados(idAfiliado)
);
CREATE TABLE ServiciosSalud (
    idServicio NUMBER PRIMARY KEY,
    fecha DATE NOT NULL,
    descripcion VARCHAR2(255) NOT NULL
);


CREATE TABLE ExamenesDiagnosticos(
    idExamen NUMBER PRIMARY KEY,
    resultados CLOB NOT NULL,
    muestras CLOB NOT NULL,
    CONSTRAINT fk_examen_serv FOREIGN KEY (idExamen)
        REFERENCES ServiciosSalud(idServicio)
        ON DELETE CASCADE
);

CREATE TABLE Consultas(
    idConsulta NUMBER PRIMARY KEY,
    tipoConsulta VARCHAR(100) NOT NULL CHECK (tipoConsulta IN ('GENERAL','ESPECIALISTA','URGENCIA','CONTROL')),
    idAfiliado NUMBER NOT NULL,
    idMedico NUMBER NULL,
    CONSTRAINT fk_consulta_serv FOREIGN KEY (idConsulta) REFERENCES ServiciosSalud(idServicio) ON DELETE CASCADE,
    FOREIGN KEY (idMedico) REFERENCES Medicos(idMedico) ON DELETE CASCADE,
    FOREIGN KEY (idAfiliado) REFERENCES Afiliados(idAfiliado) ON DELETE CASCADE
);


CREATE TABLE Terapias(
    idTerapia NUMBER PRIMARY KEY,
    tipo VARCHAR(250) NOT NULL,
    cantidadSesiones NUMBER NOT NULL,
    CONSTRAINT fk_terapia_serv FOREIGN KEY (idTerapia)
        REFERENCES ServiciosSalud(idServicio)
        ON DELETE CASCADE
);

CREATE TABLE ProcedimientosMedicos(
    idProcedimiento NUMBER PRIMARY KEY,
    tipo VARCHAR(250) NOT NULL,
    CONSTRAINT fk_proc_serv FOREIGN KEY (idProcedimiento)
        REFERENCES ServiciosSalud(idServicio)
        ON DELETE CASCADE
);
CREATE TABLE Hospitalizaciones(
    idHospitalizacion NUMBER PRIMARY KEY,
    estado VARCHAR(255) NOT NULL,
    tratamiento CLOB NOT NULL,
    CONSTRAINT fk_hosp_serv FOREIGN KEY (idHospitalizacion) REFERENCES ServiciosSalud(idServicio) ON DELETE CASCADE  
);

CREATE TABLE Afiliado_IPS(
    idAfiliado NUMBER NOT NULL,
    nit NUMBER NOT NULL, 
    PRIMARY KEY (idAfiliado,nit),
    FOREIGN KEY (idAfiliado) REFERENCES Afiliados(idAfiliado) ON DELETE CASCADE,
    FOREIGN KEY (nit) REFERENCES IPSs(nit) ON DELETE CASCADE
);



CREATE TABLE Medico_IPS(
    idMedico NUMBER NOT NULL,
    nit NUMBER NOT NULL, 
    PRIMARY KEY (idMedico,nit),
    FOREIGN KEY (idMedico) REFERENCES Medicos(idMedico) ON DELETE CASCADE,
    FOREIGN KEY (nit) REFERENCES IPSs(nit) ON DELETE CASCADE
);

CREATE TABLE Consulta_Examen(
    
    idConsulta NUMBER NOT NULL,
    idExamen NUMBER NOT NULL,
    PRIMARY KEY (idConsulta,idExamen),
    FOREIGN KEY (idConsulta) REFERENCES Consultas(idConsulta) ON DELETE CASCADE,
    FOREIGN KEY (idExamen) REFERENCES ExamenesDiagnosticos(idExamen) ON DELETE CASCADE
);

CREATE TABLE Hospitalizacion_Medico(
    idHospitalizacion NUMBER NOT NULL,
    idMedico NUMBER NOT NULL,
    PRIMARY KEY (idHospitalizacion, idMedico),
    FOREIGN KEY (idMedico) REFERENCES Medicos(idMedico) ON DELETE CASCADE,
    FOREIGN KEY (idHospitalizacion) REFERENCES Hospitalizaciones(idHospitalizacion) ON DELETE CASCADE
);

CREATE TABLE Hospitalizacion_Afiliado(
    idHospitalizacion NUMBER NOT NULL,
    idAfiliado NUMBER NOT NULL,
    PRIMARY KEY (idHospitalizacion, idAfiliado),
    FOREIGN KEY (idAfiliado) REFERENCES Afiliados(idAfiliado) ON DELETE CASCADE,
    FOREIGN KEY (idHospitalizacion) REFERENCES Hospitalizaciones(idHospitalizacion) ON DELETE CASCADE
);

CREATE TABLE Servicio_IPS(
    idServicio NUMBER NOT NULL,
    nit NUMBER NOT NULL, 
    PRIMARY KEY (idServicio,nit),
    FOREIGN KEY (idServicio) REFERENCES ServiciosSalud(idServicio) ON DELETE CASCADE,
    FOREIGN KEY (nit) REFERENCES IPSs(nit) ON DELETE CASCADE
);

CREATE TABLE Orden_Servicio(
    
    idOrden NUMBER NOT NULL,
    idServicio NUMBER NOT NULL,
    PRIMARY KEY(idOrden,idServicio),
    FOREIGN KEY (idOrden) REFERENCES OrdenServicios(idOrden) ON DELETE CASCADE,
    FOREIGN KEY (idServicio) REFERENCES ServiciosSalud(idServicio) ON DELETE CASCADE
);

CREATE TABLE Medico_Afiliado(
    idMedico NUMBER NOT NULL,
    idAfiliado NUMBER NOT NULL, 
    PRIMARY KEY (idMedico,idAfiliado),
    FOREIGN KEY (idMedico) REFERENCES Medicos(idMedico) ON DELETE CASCADE,
    FOREIGN KEY (idAfiliado) REFERENCES Afiliados(idAfiliado) ON DELETE CASCADE
    
);