CREATE TABLE Afiliado(
    idAfiliado NUMBER(20),
    tipoDocumento VARCHAR(40) NOT NULL, 
    nombre VARCHAR(50)NOT NULL, 
    fechaNacimiento DATE NOT NULL, 
    direccion VARCHAR(50) NOT NULL, 
    CONSTRAINT afiliadoPK PRIMARY KEY (idAfiliado),
);

CREATE TABLE Contribuyente(
    afiliado NUMBER, 
    CONSTRAINT AFILIADO_CONTRIBUYENTE_PK PRIMARY KEY (afiliado),
    CONSTRAINT AFILIADO_CONTRIBUYENTE_PK_FK FOREIGN KEY (afiliado) REFERENCES afiliado(idAfiliado
);

CREATE TABLE Beneficiario(
    afiliado NUMBER, 
    contribuyente NUMBER,
    parentesco VARCHAR(50) NOT NULL, 
    CONSTRAINT AFILIADO_BENEFICIARIO_PK PRIMARY KEY (afiliado, contribuyente,
    CONSTRAINT AFILIADO_BENEFICIARIO_A_PK_FK FOREIGN KEY (AFILIADO) REFERENCES AFILIADO(idAfiliado),
    CONSTRAINT AFILIADO_BENEFICIARIO_C_PK_FK FOREIGN KEY (CONTRIBUYENTE) REFERENCES AFILIADO(idAfiliado)
);

CREATE TABLE IPSs(
    nit NUMBER(15),
    nombre VARCHAR(100) NOT NULL,
    direccion VARCHAR(255) NOT NULL,
    telefono VARCHAR(20) NOT NULL,
    horario VARCHAR(50) NOT NULL,
    CONSTRAINT pk_ips PRIMARY KEY (nit)
);

CREATE TABLE Medicos(
    idMedico NUMBER GENERATED BY DEFAULT AS IDENTITY,
    identificacion VARCHAR(50) NOT NULL UNIQUE,
    nombre VARCHAR(100) NOT NULL,
    numRegistro VARCHAR(50) NOT NULL UNIQUE,
    especialidad VARCHAR(100) NOT NULL,
    CONSTRAINT pk_medico PRIMARY KEY(idMedico)
);

CREATE TABLE OrdenServicios(
    idOrden NUMBER GENERATED BY DEFAULT AS IDENTITY,
    tipoOrden VARCHAR(250) NOT NULL,
    receta VARCHAR(1000) NOT NULL,
    estado VARCHAR(150) NOT NULL CHECK(estado IN ('VIGENTE','CANCELADA','COMPLETADA')),
    fecha DATE NOT NULL,
    idMedico NUMBER NOT NULL,
    idAfiliado NUMBER NOT NULL,
    CONSTRAINT pk_ordenServicio PRIMARY KEY(idOrden),
    FOREIGN KEY (idMedico) REFERENCES Medicos(idMedico),
    FOREIGN KEY (idAfiliado) REFERENCES Afiliados(idAfiliado)
);
CREATE TABLE ServiciosSalud (
    idServicio NUMBER GENERATED BY DEFAULT AS IDENTITY,
    fecha DATE NOT NULL,
    descripcion VARCHAR2(255) NOT NULL,
    CONSTRAINT pk_servicio PRIMARY KEY(idServicio)
);


CREATE TABLE ExamenesDiagnosticos(
    idExamen NUMBER GENERATED BY DEFAULT AS IDENTITY,
    resultados VARCHAR(2000) NOT NULL,
    muestras VARCHAR(2000) NOT NULL,
    idServicio NUMBER NOT NULL,
    CONSTRAINT pk_examen PRIMARY KEY (idExamen),
    FOREIGN KEY(idServicio) REFERENCES ServiciosSalud(idServicio) ON DELETE CASCADE
);

CREATE TABLE Consultas(
    idConsulta NUMBER GENERATED BY DEFAULT AS IDENTITY,
    tipoConsulta VARCHAR(100) NOT NULL CHECK (tipoConsulta IN ('GENERAL','ESPECIALISTA','URGENCIA','CONTROL')),
    idAfiliado NUMBER NOT NULL,
    idMedico NUMBER NULL,
    idServicio NUMBER NOT NULL,
    CONSTRAINT pk_consulta_ PRIMARY KEY (idConsulta),
    FOREIGN KEY (idMedico) REFERENCES Medicos(idMedico) ON DELETE CASCADE,
    FOREIGN KEY (idAfiliado) REFERENCES Afiliados(idAfiliado) ON DELETE CASCADE,
    FOREIGN KEY(idServicio) REFERENCES ServiciosSalud(idServicio) ON DELETE CASCADE
);


CREATE TABLE Terapias(
    idTerapia NUMBER GENERATED BY DEFAULT AS IDENTITY,
    tipo VARCHAR(250) NOT NULL,
    cantidadSesiones NUMBER NOT NULL,
    idServicio NUMBER NOT NULL,
    CONSTRAINT pk_terapia PRIMARY KEY (idTerapia),
    FOREIGN KEY(idServicio) REFERENCES ServiciosSalud(idServicio) ON DELETE CASCADE 
);

CREATE TABLE ProcedimientosMedicos(
    idProcedimiento NUMBER GENERATED BY DEFAULT AS IDENTITY,
    tipo VARCHAR(250) NOT NULL,
    idServicio NUMBER NOT NULL,
    CONSTRAINT pk_procedimiento PRIMARY KEY (idProcedimiento),
    FOREIGN KEY(idServicio) REFERENCES ServiciosSalud(idServicio) ON DELETE CASCADE
);
CREATE TABLE Hospitalizaciones(
    idHospitalizacion NUMBER GENERATED BY DEFAULT AS IDENTITY,
    estado VARCHAR(255) NOT NULL,
    tratamiento VARCHAR(2000) NOT NULL,
    idServicio NUMBER NOT NULL,
    CONSTRAINT pk_hospitalizacion PRIMARY KEY (idHospitalizacion),
    FOREIGN KEY(idServicio) REFERENCES ServiciosSalud(idServicio) ON DELETE CASCADE
);

CREATE TABLE Afiliado_IPS(
    idAfiliado NUMBER NOT NULL,
    nit NUMBER NOT NULL, 
    PRIMARY KEY (idAfiliado,nit),
    FOREIGN KEY (idAfiliado) REFERENCES Afiliados(idAfiliado) ON DELETE CASCADE,
    FOREIGN KEY (nit) REFERENCES IPSs(nit) ON DELETE CASCADE
);



CREATE TABLE Medico_IPS(
    idMedico NUMBER NOT NULL,
    nit NUMBER NOT NULL, 
    PRIMARY KEY (idMedico,nit),
    FOREIGN KEY (idMedico) REFERENCES Medicos(idMedico) ON DELETE CASCADE,
    FOREIGN KEY (nit) REFERENCES IPSs(nit) ON DELETE CASCADE
);

CREATE TABLE Consulta_Examen(
    
    idConsulta NUMBER NOT NULL,
    idExamen NUMBER NOT NULL,
    PRIMARY KEY (idConsulta,idExamen),
    FOREIGN KEY (idConsulta) REFERENCES Consultas(idConsulta) ON DELETE CASCADE,
    FOREIGN KEY (idExamen) REFERENCES ExamenesDiagnosticos(idExamen) ON DELETE CASCADE
);

CREATE TABLE Hospitalizacion_Medico(
    idHospitalizacion NUMBER NOT NULL,
    idMedico NUMBER NOT NULL,
    PRIMARY KEY (idHospitalizacion, idMedico),
    FOREIGN KEY (idMedico) REFERENCES Medicos(idMedico) ON DELETE CASCADE,
    FOREIGN KEY (idHospitalizacion) REFERENCES Hospitalizaciones(idHospitalizacion) ON DELETE CASCADE
);

CREATE TABLE Hospitalizacion_Afiliado(
    idHospitalizacion NUMBER NOT NULL,
    idAfiliado NUMBER NOT NULL,
    PRIMARY KEY (idHospitalizacion, idAfiliado),
    FOREIGN KEY (idAfiliado) REFERENCES Afiliados(idAfiliado) ON DELETE CASCADE,
    FOREIGN KEY (idHospitalizacion) REFERENCES Hospitalizaciones(idHospitalizacion) ON DELETE CASCADE
);

CREATE TABLE Ips_Servicio (
    IPSs NUMBER,
    SERVICIOSSALUD VARCHAR(100),
    CONSTRAINT IPS_SERVICIO_PK PRIMARY KEY (IPSs, SERVICIOSSALUD),
    CONSTRAINT IPS_SERVICIO_IPS_FK FOREIGN KEY (IPSs) REFERENCES IPSs(NIT)
);

CREATE TABLE Orden_Servicio(
    
    idOrden NUMBER NOT NULL,
    idServicio NUMBER NOT NULL,
    PRIMARY KEY(idOrden,idServicio),
    FOREIGN KEY (idOrden) REFERENCES OrdenServicios(idOrden) ON DELETE CASCADE,
    FOREIGN KEY (idServicio) REFERENCES ServiciosSalud(idServicio) ON DELETE CASCADE
);

CREATE TABLE Medico_Afiliado(
    idMedico NUMBER NOT NULL,
    idAfiliado NUMBER NOT NULL, 
    PRIMARY KEY (idMedico,idAfiliado),
    FOREIGN KEY (idMedico) REFERENCES Medicos(idMedico) ON DELETE CASCADE,
    FOREIGN KEY (idAfiliado) REFERENCES Afiliados(idAfiliado) ON DELETE CASCADE
    
);

CREATE SEQUENCE AFILIADO_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE MEDICO_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IPS_SEQUENCE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SERVICIO_SEQUENCE START WITH 1 INCREMENT BY 1;
